services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sgmi?schema=public
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sgmi-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sgmi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sgmi"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - sgmi-network

volumes:
  dbdata:
    driver: local

networks:
  sgmi-network:
    driver: bridge
